"""
任务生成器 - 生成批量 Workflower 调用脚本和任务清单
"""

import json
from pathlib import Path
from typing import List, Dict


def generate_task_script(
    workflow_dirs: List[Path],
    cluster_metadata: List[Dict],
    output_path: Path,
    mode: str = "sequential"
) -> None:
    """
    生成批量调用 Workflower 的脚本

    Args:
        workflow_dirs: Workflower 输入目录列表
        cluster_metadata: 对应的聚类元数据列表
        output_path: 输出脚本路径
        mode: 执行模式（sequential 或 parallel）
    """
    if mode == "sequential":
        _generate_sequential_script(workflow_dirs, cluster_metadata, output_path)
    elif mode == "parallel":
        _generate_parallel_script(workflow_dirs, cluster_metadata, output_path)
    else:
        raise ValueError(f"Unknown mode: {mode}")


def _generate_sequential_script(
    workflow_dirs: List[Path],
    cluster_metadata: List[Dict],
    output_path: Path
) -> None:
    """生成顺序执行脚本"""
    lines = [
        "#!/bin/bash",
        "# Auto-generated by Step2: Workflow extraction task script",
        "# This script guides you through processing each cluster with Workflower",
        "",
        "set -e",
        "",
        "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
        "",
    ]

    for i, (workflow_dir, meta) in enumerate(zip(workflow_dirs, cluster_metadata), 1):
        cluster_id = meta["local_cluster_id"]
        num_chains = meta["num_chains"]
        num_papers = meta["num_papers"]
        domain = meta["domain"]

        # 使用相对路径
        rel_path = workflow_dir.relative_to(output_path.parent.parent)

        lines.extend([
            f"# ========================================",
            f"# Task {i}/{len(workflow_dirs)}: Cluster {cluster_id}",
            f"# Domain: {domain}",
            f"# Chains: {num_chains}, Papers: {num_papers}",
            f"# ========================================",
            f"",
            f"echo \"\"",
            f"echo \"========================================\"",
            f"echo \"Task {i}/{len(workflow_dirs)}: Processing cluster_{cluster_id}\"",
            f"echo \"Domain: {domain}\"",
            f"echo \"Chains: {num_chains}, Papers: {num_papers}\"",
            f"echo \"Directory: {rel_path}\"",
            f"echo \"========================================\"",
            f"echo \"\"",
            f"",
            f"cd \"$SCRIPT_DIR/{rel_path}\"",
            f"",
            f"echo \"Please open Claude Code and run the following command:\"",
            f"echo \"  /workflower-v2\"",
            f"echo \"\"",
            f"echo \"Or provide a prompt like:\"",
            f"echo \"  提取 cluster_{cluster_id} 的工作流并生成综述\"",
            f"echo \"\"",
            f"read -p \"Press Enter when Workflower completes for cluster_{cluster_id}...\"",
            f"",
            f"# Verify outputs",
            f"if [ ! -f \"workflow_structure.json\" ]; then",
            f"    echo \"⚠ Warning: workflow_structure.json not found. Workflower may not have completed.\"",
            f"    read -p \"Continue anyway? (y/n) \" -n 1 -r",
            f"    echo",
            f"    if [[ ! $REPLY =~ ^[Yy]$ ]]; then",
            f"        echo \"Aborted.\"",
            f"        exit 1",
            f"    fi",
            f"fi",
            f"",
            f"echo \"✓ Cluster {cluster_id} completed\"",
            f"echo \"\"",
            f"",
        ])

    lines.extend([
        "echo \"\"",
        "echo \"========================================\"",
        "echo \"All tasks completed!\"",
        "echo \"========================================\"",
        "",
    ])

    output_path.write_text("\n".join(lines), encoding="utf-8")
    output_path.chmod(0o755)  # Make executable


def _generate_parallel_script(
    workflow_dirs: List[Path],
    cluster_metadata: List[Dict],
    output_path: Path
) -> None:
    """生成并行任务脚本（生成多个独立脚本）"""
    base_dir = output_path.parent
    base_name = output_path.stem

    # 为每个聚类生成独立脚本
    for i, (workflow_dir, meta) in enumerate(zip(workflow_dirs, cluster_metadata), 1):
        cluster_id = meta["local_cluster_id"]
        num_chains = meta["num_chains"]
        num_papers = meta["num_papers"]
        domain = meta["domain"]

        script_path = base_dir / f"{base_name}_cluster_{cluster_id}.sh"
        rel_path = workflow_dir.relative_to(base_dir.parent)

        lines = [
            "#!/bin/bash",
            f"# Task {i}/{len(workflow_dirs)}: Cluster {cluster_id}",
            f"# Domain: {domain}, Chains: {num_chains}, Papers: {num_papers}",
            "",
            "set -e",
            "",
            "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
            "",
            f"cd \"$SCRIPT_DIR/../{rel_path}\"",
            "",
            f"echo \"Processing cluster_{cluster_id}...\"",
            f"echo \"Domain: {domain}\"",
            f"echo \"Chains: {num_chains}, Papers: {num_papers}\"",
            f"echo \"Directory: $(pwd)\"",
            f"echo \"\"",
            f"echo \"Please open Claude Code and run:\"",
            f"echo \"  /workflower-v2\"",
            f"echo \"\"",
            f"read -p \"Press Enter when completed...\"",
            "",
        ]

        script_path.write_text("\n".join(lines), encoding="utf-8")
        script_path.chmod(0o755)

    # 生成主脚本（列出所有子脚本）
    lines = [
        "#!/bin/bash",
        "# Parallel workflow extraction - Master script",
        "# Run individual cluster scripts in separate terminals",
        "",
        "echo \"Parallel workflow extraction tasks:\"",
        "echo \"\"",
    ]

    for i, meta in enumerate(cluster_metadata, 1):
        cluster_id = meta["local_cluster_id"]
        script_name = f"{base_name}_cluster_{cluster_id}.sh"
        lines.append(f"echo \"  {i}. ./{script_name}  (cluster_{cluster_id})\"")

    lines.extend([
        "",
        "echo \"\"",
        "echo \"Run each script in a separate terminal to process clusters in parallel.\"",
        "",
    ])

    output_path.write_text("\n".join(lines), encoding="utf-8")
    output_path.chmod(0o755)


def generate_task_manifest(
    workflow_dirs: List[Path],
    cluster_metadata: List[Dict],
    output_path: Path
) -> None:
    """
    生成任务清单 JSON 文件

    Args:
        workflow_dirs: Workflower 输入目录列表
        cluster_metadata: 对应的聚类元数据列表
        output_path: 输出 JSON 路径
    """
    tasks = []

    for workflow_dir, meta in zip(workflow_dirs, cluster_metadata):
        task = {
            "cluster_id": meta["local_cluster_id"],
            "global_cluster_id": meta["global_cluster_id"],
            "domain": meta["domain"],
            "directory": str(workflow_dir),
            "num_chains": meta["num_chains"],
            "num_papers": meta["num_papers"],
            "avg_intra_similarity": float(meta["avg_intra_similarity"]),
            "status": "pending",
            "outputs": {
                "workflow_structure.json": False,
                "paper_extractions.yaml": False,
                "workflow_3layer.md": False,
                "review.pdf": False,
                "decision_tree.pdf": False,
            }
        }
        tasks.append(task)

    manifest = {
        "total_tasks": len(tasks),
        "completed": 0,
        "pending": len(tasks),
        "tasks": tasks
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
